- name: setup_nfs_servers [debian] | create nfs directory
  file:
    path: "{{ nfs_path }}"
    mode: "0777"
    owner: nobody
    group: nogroup
    state: directory
    recurse: yes

- name: setup_nfs_servers [debian] | create /etc/exports.d directory
  file:
    path: "/etc/exports.d"
    mode: "644"
    state: directory

- name: setup_nfs_servers [debian] | install /etc/exports.d/nfs.exports
  template:
    src: etc/exports.d/nfs.exports.j2
    dest: "/etc/exports.d/nfs.exports"

- name: setup_nfs_servers [debian] | restart nfs-kernel-server
  systemd:
    name: nfs-kernel-server
    state: restarted
