- name: setup_nfs_server | configure | create nfs directories
  file:
    path: "{{ item }}"
    mode: 0777
    owner: nobody
    group: nogroup
    state: directory
  with_items:
    - "{{ nfs_path }}"
    - "{{ cinder_backup_nfs_path }}"

- name: setup_nfs_server | configure | create /etc/exports.d directory
  file:
    path: "/etc/exports.d"
    state: directory

- name: setup_nfs_server | configure | install /etc/exports.d/nfs-cinder-backup.exports
  template:
    src: etc/exports.d/nfs-cinder-backup.exports.j2
    dest: "/etc/exports.d/nfs-cinder-backup.exports"

- name: setup_nfs_server | configure | restart nfs-kernel-server
  systemd:
    name: nfs-kernel-server
    state: restarted
