k8s_requirements:
  - kubeadm
  - kubectl
  - kubelet
  - helm

k8s_requirements_pip:
  - PyYAML

k8s_kubeconfig_path: "{{ ansible_env.HOME }}/.kube/config"

k8s_configs:
  debian:
    k8s:
      repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    helm:
      repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
      key: https://baltocdn.com/helm/signing.asc
