- name: setup_system | install $HOME/.*
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "644"
  with_items:
    - bash_configs.d/
    - bash_aliases
    - bash_profile
    - bashrc
    - inputrc
    - tmux.conf
    - vimrc

- name: setup_system | install $HOME/.*
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items:
    - bash_configs.d/k8s.sh

- name: setup_system | install etc/ansible/*
  copy:
    src: etc/ansible
    dest: /etc/
    mode: "644"
  become: yes

- name: setup_system | install ssh/config
  copy:
    src: "ssh/config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: "644"
    force: no
