- name: setup_system | create ~/.* directories
  file:
    path: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "744"
    state: directory
    recurse: yes
  with_items:
    - bash_configs.d

- name: setup_system | install etc/ansible/*
  copy:
    src: etc/ansible
    dest: /etc/
    mode: "644"
  become: yes

- name: setup_system | install ssh/config
  copy:
    src: "ssh/config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: "644"
    force: no

- name: setup_system | install $HOME/.*
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "644"
  with_items:
    - bash_configs.d/airflow.sh
    - bash_configs.d/bash.sh
    - bash_configs.d/brew.sh
    - bash_configs.d/ps1.sh
    - bash_configs.d/python.sh
    - bash_configs.d/ruby.sh
    - bash_configs.d/yandex.sh
    - bash_aliases
    - bash_profile
    - bashrc
    - inputrc
    - tmux.conf
