- name: setup_system | install configs
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "644"
  with_items:
    - bash_aliases
    - bash_profile
    - bashrc
    - inputrc
    - python.conf
    - ruby.conf
    - vim.conf
    - vimrc

- name: setup_system | install ssh config
  copy:
    src: "ssh/config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: "644"
    force: no
