- import_tasks: packages_debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: packages_darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: packages_debian_vim.yml
  when: ansible_os_family == "Debian" and
        setup_vim | d("no") == "yes"

- import_tasks: packages_debian_libvirt.yml
  become: yes
  when: ansible_os_family == "Debian" and
        setup_libvirt | d("no") == "yes"

- import_tasks: packages_pip.yml

- import_tasks: packages_pip_libvirt.yml
  when: setup_libvirt | d("no") == "yes"

- import_tasks: sources.yml

- import_tasks: configs.yml

- import_tasks: configs_debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: configs_vim.yml
  when: setup_vim | d("no") == "yes"

- import_tasks: configs_debian_libvirt.yml
  become: yes
  when: ansible_os_family == "Debian" and
        setup_libvirt | d("no") == "yes"
