- name: setup_python | install -U pip
  pip:
    name: pip
    extra_args: "-U"

- name: setup_python | install requirements [pip]
  pip:
    name: "{{ python_requirements_pip }}"

- name: setup_python | install requirements [pip, jupyter]
  pip:
    name: "{{ python_requirements_pip_jupyter }}"
