- name: setup_system | git co sources
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: True
    dest: "{{ item.location }}"
    update: no
  with_items:
    - "{{ python_requirements_sources }}"
