- name: setup_ml | create /etc/nginx/templates
  file:
    path: "/etc/nginx/templates"
    mode: "755"
    state: directory
    recurse: yes
  become: yes

- name: setup_ml | install /etc/*
  template:
    src: "etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
  become: yes
  with_items:
    - nginx/templates/default.conf.template

- name: setup_ml | install docker-compose.yaml
  template:
    src: "docker-compose.yaml.j2"
    dest: "{{ ml_projects_dir }}/docker-compose.yaml"
