- name: setup_ml | create /etc/nginx/* directories [nginx]
  file:
    path: "/etc/nginx/{{ item }}"
    mode: "755"
    state: directory
    recurse: yes
  with_items:
    - templates

- name: setup_ml | install /etc/nginx/* [nginx]
  template:
    src: "etc/nginx/{{ item }}.j2"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - templates/default.conf.template
