- import_tasks: packages_pip.yml

- import_tasks: sources.yml
  when: download_sources | d("no") == "yes"

- import_tasks: configs_airflow.yml
  become: yes

- import_tasks: configs_nginx.yml
  become: yes

- import_tasks: configs.yml
