- name: setup_nfs | create nfs directory [client]
  file:
    path: "{{ nfs_path }}"
    mode: "0777"
    owner: nobody
    group: nogroup
    state: directory
    recurse: yes

- name: setup_nfs | create /etc/fstab.d directory [client]
  file:
    path: "/etc/fstab.d"
    mode: "644"
    state: directory

- name: setup_nfs | install /etc/fstab.d/nfs.fstab [client]
  template:
    src: etc/fstab.d/nfs.fstab.j2
    dest: "/etc/fstab.d/nfs.fstab"
