- name: setup_docker | pull registry image [registry]
  docker_image:
    name: "registry:2"
    source: pull

- name: setup_docker | create and run registry container [registry]
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
      - "4000:5000"
    volumes:
      - registry:/var/lib/registry
