- name: setup_docker | create /etc/docker directory [registry]
  file:
    path: "/etc/docker"
    state: directory

- name: setup_docker | install etc/docker/daemon.json [registry]
  template:
    src: etc/docker/daemon.json.j2
    dest: "/etc/docker/daemon.json"

- name: setup_docker [debian] | restart docker [registry]
  systemd:
    name: docker
    state: restarted
  become: yes
  when: ansible_os_family == "Debian"

- name: setup_docker | pull registry image [registry]
  docker_image:
    name: "registry:2"
    source: pull

- name: setup_docker | create and run registry container [registry]
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
      - "{{ docker_insecure_registries_port }}:5000"
    volumes:
      - registry:/var/lib/registry
