system_requirements:
  - tmux

system_requirements_debian:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - locales
  - software-properties-common

system_sources_path: "{{ ansible_env.HOME }}/Projects"

system_requirements_sources:
  - name: ceph-deploy
    repo: https://github.com/ceph/ceph-deploy.git
    location: "{{ system_sources_path }}/ceph-deploy"
