system_requirements:
  - tmux

system_requirements_debian:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - locales
  - software-properties-common

  # Build dependencies.
  - autoconf
  - automake
  - autotools-dev
  - binutils
  - gcc
  - g++
  - make
  - pkg-config
  - sed
