#################
# Network options
#################

network_requirements_debian:
  - iproute2

network_interfaces:
  desktop1:
    gateway:
      name: "enp7s0"
      cidr: "192.168.0.70/24"
      addr: "192.168.0.70"

  master1:
    gateway:
      name: "eth0"
      cidr: "10.129.0.17/24"
      addr: "10.129.0.17"

################
# Docker options
################

docker_insecure_registries:
  - "{{ network_interfaces[inventory_hostname].gateway.addr }}"

docker_insecure_registries_port: "4000"

####################
# PostgreSQL options
####################

############
# ML options
############

ml_requirements_pip:
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - seaborn
  - scipy
  - sklearn

  # Python extension for computing string edit
  # distances and similarities.
  - python-Levenshtein

  # Gensim is a Python library for topic modelling,
  # document indexing and similarity retrieval
  # with large corpora.
  # https://github.com/RaRe-Technologies/gensim
  - gensim

  # It is little word cloud generator in Python.
  # https://github.com/amueller/word_cloud
  - wordcloud

ml_projects_path: "{{ ansible_env.HOME }}/Projects"

ml_sources:
    repo: https://github.com/yandexdataschool/nlp_course.git
    location: "{{ ml_projects_path }}/nlp_course"
