openvpn_servers:
  - proto: udp
    port: 1194
    mask: "255.255.255.0"
    cidr: "10.9.0.0/24"
    network: "10.9.0.0"

openvpn_clients:
  - hostname: "desktop1"
    vpn_ipv4: "10.9.0.2"
    vpn_mask: "255.255.255.0"

  - hostname: "dell"
    vpn_ipv4: "10.9.0.3"
    vpn_mask: "255.255.255.0"
