- name: setup_network [debian] | install if-{up,down}.d/k8s_interfaces [k8s]
  template:
    src: etc/network/{{ item }}/k8s_interfaces.j2
    dest: "/etc/network/{{ item }}/k8s_interfaces"
    mode: a+x
  with_items:
    - "if-up.d"
    - "if-down.d"
