- name: setup_libvirt | define networks
  community.libvirt.virt_net:
    command: define
    name: "{{ item.name }}"
    xml: '{{ lookup("template", item.template) }}'
  with_items: "{{ libvirt_networks }}"

- name: setup_libvirt | create networks
  community.libvirt.virt_net:
    command: create
    name: "{{ item.name }}"
  with_items: "{{ libvirt_networks }}"
