############
# ML options
############

ml_requirements_pip:
  - boto3
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - scipy
  - sklearn
  - xgboost

  #############################
  # Data visualization tools. #
  #############################

  - matplotlib
  - seaborn

  # Palettable is a library of color palettes for Python.
  - palettable

  # To use plotly in JupyterLab, install the ipywidgets packages,
  # nodjs>=12.0.0 and npm.
  #
  # https://github.com/nodesource/distributions/
  # curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  # sudo apt-get install -y nodejs
  #
  # https://plotly.com/python/getting-started/
  # jupyter labextension install jupyterlab-plotly@4.14.3
  # jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.14.3
  - plotly
  - ipywidgets>=7.5

  #######
  # NLP #
  #######

  # spaCy is a free open-source library for Natural
  # Language Processing in Python.
  - spacy

  # Natural Language Toolkit.
  - nltk

  # Python extension for computing string edit
  # distances and similarities.
  - python-Levenshtein

  # Gensim is a Python library for topic modelling,
  # document indexing and similarity retrieval
  # with large corpora.
  # https://github.com/RaRe-Technologies/gensim
  - gensim

  # It is little word cloud generator in Python.
  # https://github.com/amueller/word_cloud
  - wordcloud

ml_projects_dir: "{{ ansible_env.HOME }}/Projects/ml"

ml_projects_src:
  - repo: https://github.com/yandexdataschool/nlp_course.git
    location: "{{ ml_projects_dir }}/nlp_course"

  - repo: https://github.com/lazyprogrammer/machine_learning_examples
    location: "{{ ml_projects_dir }}/machine_learning_examples"

  - repo: https://github.com/RaRe-Technologies/gensim
    location: "{{ ml_projects_dir }}/gensim"

################
# Docker options
################

docker_image_prefix: "cr.yandex/crpfkr3l4bf2abli6nt1/"

###############
# Nginx options
###############

nginx_port: 80
nginx_docker_tag: 1.21

###############
# Redis options
###############

redis_port: 6379
redis_docker_tag: 6

####################
# PostgreSQL options
####################

postgres_port: 5432
postgres_docker_tag: 13.3

postgres_db: airflow
postgres_user: airflow
postgres_password: airflow

#################
# Airflow options
#################

airflow_docker_tag: 2.1.0
airflow_webserver_port: 8080
airflow_flower_port: 5555

airflow_init_user: airflow
airflow_init_password: airflow

airflow_logs_dir: "/var/log/airflow"
airflow_dags_dir: "{{ ml_projects_dir }}/mlexp/airflow/dags"
airflow_plugins_dir: "{{ ml_projects_dir }}/mlexp/airflow/plugins"
