################
# Docker options
################

docker_image_prefix: "cr.yandex/crpfkr3l4bf2abli6nt1/"

###############
# Nginx options
###############

nginx_port: 80
nginx_docker_tag: 1.21

###############
# Redis options
###############

redis_port: 6379
redis_docker_tag: 6

####################
# PostgreSQL options
####################

postgres_port: 5432
postgres_docker_tag: 13.3

postgres_db: airflow
postgres_user: airflow
postgres_password: airflow

############
# ML options
############

ml_requirements_pip:
  - boto3

  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - seaborn
  - scipy
  - sklearn

  # Python extension for computing string edit
  # distances and similarities.
  - python-Levenshtein

  # Gensim is a Python library for topic modelling,
  # document indexing and similarity retrieval
  # with large corpora.
  # https://github.com/RaRe-Technologies/gensim
  - gensim

  # It is little word cloud generator in Python.
  # https://github.com/amueller/word_cloud
  - wordcloud

ml_projects_dir: "{{ ansible_env.HOME }}/Projects/ml"

ml_projects_src:
  - repo: https://github.com/yandexdataschool/nlp_course.git
    location: "{{ ml_projects_dir }}/nlp_course"

  - repo: https://github.com/lazyprogrammer/machine_learning_examples
    location: "{{ ml_projects_dir }}/machine_learning_examples"

  - repo: https://github.com/RaRe-Technologies/gensim
    location: "{{ ml_projects_dir }}/gensim"
