- name: setup_kolla | install etc/kolla/* [ceph]
  copy:
    src: "ceph/etc/kolla/{{ item }}"
    dest: "/etc/kolla/{{ item }}"
    mode: "755"
  with_items:
    - config/cinder/cinder-backup.conf
    - config/cinder/cinder-volume.conf
    - config/glance/glance-api.conf
    - config/nova/nova-compute.conf

- name: setup_kolla | install etc/kolla/* [ceph]
  template:
    src: "ceph/etc/kolla/{{ item }}.j2"
    dest: "/etc/kolla/{{ item }}"
  with_items:
    - config/karbor/karbor-protection/providers.d/noop.conf
    - config/karbor/karbor-protection/providers.d/openstack-infra.conf
    - config/karbor/karbor-protection/providers.d/openstack-infra-volume-snapshot.conf
    - globals.yml

- stat: path="/etc/ceph/ceph.conf"
  register: stat_ceph_config

- assert:
    that: stat_ceph_config.stat.isreg | d(False) == True

- stat: path="/etc/ceph/ceph.client.glance.keyring"
  register: stat_ceph_glance_keyring

- assert:
    that: stat_ceph_glance_keyring.stat.isreg | d(False) == True

- stat: path="/etc/ceph/ceph.client.cinder.keyring"
  register: stat_ceph_cinder_keyring

- assert:
    that: stat_ceph_cinder_keyring.stat.isreg | d(False) == True

- stat: path="/etc/ceph/ceph.client.cinder-backup.keyring"
  register: stat_ceph_cinder_backup_keyring

- assert:
    that: stat_ceph_cinder_backup_keyring.stat.isreg | d(False) == True

- name: setup_kolla | install etc/kolla/config/*/ceph.conf [ceph]
  copy:
    src: "/etc/ceph/ceph.conf"
    dest: "/etc/kolla/config/{{ item }}/ceph.conf"
  with_items:
    - cinder
    - glance
    - nova

- name: setup_kolla | install keyrings [ceph, glance]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/glance/{{ item }}"
  with_items:
    - ceph.client.glance.keyring

- name: setup_kolla | install keyrings [ceph, cinder-volume]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/cinder/cinder-volume/{{ item }}"
  with_items:
    - ceph.client.cinder.keyring

- name: setup_kolla | install keyrings [ceph, cinder-backup]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/cinder/cinder-backup/{{ item }}"
  with_items:
    - ceph.client.cinder.keyring
    - ceph.client.cinder-backup.keyring

- name: setup_kolla | install keyrings [ceph, nova]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/nova/{{ item }}"
  with_items:
    - ceph.client.cinder.keyring
