- name: setup_kolla | install etc/kolla/config/* [ceph]
  copy:
    src: "etc/kolla/config/ceph/{{ item }}"
    dest: "/etc/kolla/config/{{ item }}"
    mode: "755"
  with_items:
    - cinder/cinder-backup.conf
    - cinder/cinder-volume.conf
    - glance/glance-api.conf
    - karbor/karbor-protection/providers.d/noop.conf
    - karbor/karbor-protection/providers.d/openstack-infra.conf
    - karbor/karbor-protection/providers.d/openstack-infra-volume-snapshot.conf
    - nova/nova-compute.conf

- name: setup_kolla | install etc/kolla/* [ceph]
  template:
    src: "etc/kolla/ceph/{{ item }}.j2"
    dest: "/etc/kolla/{{ item }}"
  with_items:
    - globals.yml

- name: setup_kolla | install etc/kolla/config/*/ceph.conf [ceph]
  copy:
    src: "/etc/ceph/ceph.conf"
    dest: "/etc/kolla/config/{{ item }}/ceph.conf"
  with_items:
    - cinder
    - glance
    - nova

- name: setup_kolla | install keyrings [ceph, glance]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/glance/{{ item }}"
  with_items:
    - ceph.client.glance.keyring

- name: setup_kolla | install keyrings [ceph, cinder-volume]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/cinder/cinder-volume/{{ item }}"
  with_items:
    - ceph.client.cinder.keyring

- name: setup_kolla | install keyrings [ceph, cinder-backup]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/cinder/cinder-backup/{{ item }}"
  with_items:
    - ceph.client.cinder.keyring
    - ceph.client.cinder-backup.keyring

- name: setup_kolla | install keyrings [ceph, nova]
  copy:
    src: "/etc/ceph/{{ item }}"
    dest: "/etc/kolla/config/nova/{{ item }}"
  with_items:
    - ceph.client.cinder.keyring
