- name: setup_kolla | create /etc/kolla/config directory [common]
  file:
    path: "/etc/kolla/config"
    mode: "755"
    state: directory
    recurse: yes

- name: setup_kolla | install etc/kolla/config [common]
  copy:
    src: "etc/kolla/config/common/{{ item }}"
    dest: "/etc/kolla/config/{{ item }}"
    mode: "755"
  with_items:
    - karbor.conf
    - neutron/

- name: setup_kolla | install etc/kolla/kolla-build.conf [common]
  template:
    src: etc/kolla/kolla-build.conf.j2
    dest: "/etc/kolla/kolla-build.conf"
