- name: setup_kolla [debian] | enable IPv4 forwarding [NetworkManager]
  sysctl: name=net.ipv4.ip_forward value=1

- name: setup_kolla [debian] | create if-{up,down}.d directories [NetworkManager]
  file:
    path: "/etc/network/{{ item }}"
    state: directory
  with_items:
    - "if-up.d"
    - "if-down.d"

- name: setup_kolla [debian] | install /etc/* [NetworkManager]
  template:
    src: "common/etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - netplan/99-kolla.yaml

- name: setup_kolla [debian] | install /etc/* [NetworkManager, a+x]
  template:
    src: "common/etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: a+x
  with_items:
    - network/if-up.d/kolla_interfaces
    - network/if-down.d/kolla_interfaces
