- import_tasks: packages_debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: packages_debian_nm.yml
  become: yes
  when: ansible_os_family == "Debian" and
        network_manager_type | d("NetworkManager") == "NetworkManager"

- import_tasks: packages_debian_ceph.yml
  become: yes
  when: ansible_os_family == "Debian" and
        storage_backend_type == "ceph"

- import_tasks: configs_debian_nm.yml
  become: yes
  when: ansible_os_family == "Debian" and
        network_manager_type | d("NetworkManager") == "NetworkManager"

- import_tasks: configs_common.yml
  become: yes

- import_tasks: configs_lvm.yml
  become: yes
  when: storage_backend_type == "lvm"

- import_tasks: configs_ceph.yml
  become: yes
  when: storage_backend_type == "ceph"
