- import_tasks: packages_debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: sources.yml

- import_tasks: configs.yml
  become: yes

- import_tasks: configs_lvm.yml
  become: yes
  when: storage_backend_type == "lvm"

- import_tasks: configs_ceph.yml
  become: yes
  when: storage_backend_type == "ceph"
