- name: setup_kolla | create openstack_sources_path
  file:
    path: "{{ openstack_sources_path }}"
    state: directory

- name: setup_kolla | git co sources
  git:
    repo: "{{ item.repo }}"
    version: "{{ openstack_versions[openstack_release][item.name] }}"
    accept_hostkey: True
    dest: "{{ item.location }}"
    update: no
  with_items:
    - "{{ openstack_requirements_sources }}"
