- name: setup_ovs [debian] | enable IPv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1

- name: setup_ovs [debian] | enable IPv6 forwarding
  sysctl: name=net.ipv6.conf.all.forwarding value=1

- name: setup_ovs [debian] | create ovs bridges
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: "{{ item.name }}"
    state: present
  with_items:
    - "{{ ovs_bridges }}"

- name: setup_ovs [debian] | create ovs bridges [ports]
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: "{{ item.1.name }}"
    parent: "{{ item.0.name }}"
    vlan: "{{ item.1.vlan }}"
    state: present
  with_subelements:
    - "{{ ovs_bridges }}"
    - "children"
