# Possible values:
# - binary
# - source
kolla_install_type: source

# Possible values:
# - centos
# - debian
# - ubuntu
# - rhel
kolla_base_distro: debian

kolla_docker_namespace: kolla

kolla_docker_registry: "192.168.0.75:4000"

kolla_network_interface: macvlan0
kolla_neutron_external_interface: macvtap0

kolla_internal_vip_address: "192.168.0.10"
kolla_external_vip_address: "192.168.0.11"
