- name: openvpn_add_clients | configure | install client configs
  template:
    src: etc_openvpn_client.conf.j2
    dest: "{{ openvpn_path }}/client/client-{{ item.hostname }}.conf"
  delegate_to: "{{ item.hostname }}"
  with_items: "{{ openvpn_new_clients }}"

- name: openvpn_add_clients | configure | create ccd dir
  file:
    path: "{{ openvpn_path_ccd }}"
    state: directory

- name: openvpn_add_clients | configure | install client configs
  copy:
    content: "ifconfig-push {{ item.vpn_ipv4 }} {{ item.vpn_mask }}"
    dest: "{{ openvpn_path_ccd }}/client@{{ item.hostname }}"
  with_items: "{{ openvpn_new_clients }}"
